from enum import Enum


class EventType(str, Enum):
    NETWORK_SWITCH = "NETWORK_SWITCH"
    NETWORK_STATUS_CHANGE = "NETWORK_STATUS_CHANGE"
    NETWORK_LOST = "NETWORK_LOST"
    NETWORK_RESTORED = "NETWORK_RESTORED"
